const timesData = [
    // === POTE A (Os 4 Grandes) ===
    {
        id: "corinthians",
        nome: "Corinthians",
        apelido: "Timão",
        pote: "A",
        estadio: "Neo Química Arena",
        capacidade: 48905,
        moral: 50,
        status: "Normal",
        cor: "#000000",
        jogadores: [
            { nome: "Hugo Souza", pos: "GOL", num: 1, forca: 84 },
            { nome: "Matheusinho", pos: "LAT", num: 2, forca: 79 }, // Alterado
            { nome: "André Ramalho", pos: "ZAG", num: 5, forca: 82 },
            { nome: "Gustavo Henrique", pos: "ZAG", num: 4, forca: 78 },
            { nome: "Matheus Bidu", pos: "LAT", num: 21, forca: 77 },
            { nome: "José Martínez", pos: "MEI", num: 70, forca: 80 },
            { nome: "Breno Bidon", pos: "MEI", num: 7, forca: 77 }, // Alterado
            { nome: "R. Garro", pos: "MEI", num: 10, forca: 88 },
            { nome: "Memphis Depay", pos: "ATA", num: 94, forca: 91 },
            { nome: "Yuri Alberto", pos: "ATA", num: 9, forca: 85 },
            { nome: "Talles Magno", pos: "ATA", num: 43, forca: 81 },
            // Reservas
            { nome: "Donelli", pos: "GOL", num: 32, forca: 72 },
            { nome: "Félix Torres", pos: "ZAG", num: 3, forca: 79 },
            { nome: "Charles", pos: "MEI", num: 8, forca: 76 },
            { nome: "Romero", pos: "ATA", num: 11, forca: 78 }
        ]
    },
    // ... Mantenha o restante dos times (Palmeiras, SPFC, etc) igual ao anterior ...
    // Se quiser, posso mandar o arquivo data.js inteiro de novo, mas se você já salvou, só altere o Corinthians.
    // Para garantir que funcione, vou assumir que você tem o restante dos dados.
    // Cole aqui o restante dos times do JSON anterior...
    {
        id: "palmeiras",
        nome: "Palmeiras",
        apelido: "Verdão",
        pote: "A",
        estadio: "Allianz Parque",
        capacidade: 43713,
        moral: 60,
        status: "Confiança Alta",
        cor: "#006437",
        jogadores: [
            { nome: "Weverton", pos: "GOL", num: 21, forca: 89 },
            { nome: "Mayke", pos: "LAT", num: 12, forca: 80 },
            { nome: "Gómez", pos: "ZAG", num: 15, forca: 88 },
            { nome: "Murilo", pos: "ZAG", num: 26, forca: 86 },
            { nome: "Piquerez", pos: "LAT", num: 22, forca: 85 },
            { nome: "Aníbal Moreno", pos: "MEI", num: 5, forca: 84 },
            { nome: "Zé Rafael", pos: "MEI", num: 8, forca: 81 },
            { nome: "Raphael Veiga", pos: "MEI", num: 23, forca: 89 },
            { nome: "Felipe Anderson", pos: "MEI", num: 9, forca: 86 },
            { nome: "Dudu", pos: "ATA", num: 7, forca: 83 },
            { nome: "Flaco López", pos: "ATA", num: 42, forca: 82 },
            { nome: "Marcelo Lomba", pos: "GOL", num: 14, forca: 75 },
            { nome: "Vitor Reis", pos: "ZAG", num: 44, forca: 79 },
            { nome: "Maurício", pos: "MEI", num: 18, forca: 80 },
            { nome: "Rony", pos: "ATA", num: 10, forca: 79 }
        ]
    },
    {
        id: "saopaulo",
        nome: "São Paulo",
        apelido: "Tricolor",
        pote: "A",
        estadio: "MorumBIS",
        capacidade: 72039,
        moral: 50,
        status: "Normal",
        cor: "#c61d1d",
        jogadores: [
            { nome: "Rafael", pos: "GOL", num: 23, forca: 84 },
            { nome: "Rafinha", pos: "LAT", num: 13, forca: 77 },
            { nome: "Arboleda", pos: "ZAG", num: 5, forca: 85 },
            { nome: "Alan Franco", pos: "ZAG", num: 28, forca: 82 },
            { nome: "Welington", pos: "LAT", num: 6, forca: 79 },
            { nome: "Luiz Gustavo", pos: "MEI", num: 16, forca: 81 },
            { nome: "Bobadilla", pos: "MEI", num: 21, forca: 78 },
            { nome: "Lucas Moura", pos: "MEI", num: 7, forca: 89 },
            { nome: "Luciano", pos: "ATA", num: 10, forca: 83 },
            { nome: "Ferreira", pos: "ATA", num: 47, forca: 81 },
            { nome: "Calleri", pos: "ATA", num: 9, forca: 88 },
            { nome: "Jandrei", pos: "GOL", num: 93, forca: 74 },
            { nome: "Sabino", pos: "ZAG", num: 35, forca: 76 },
            { nome: "Nestor", pos: "MEI", num: 11, forca: 78 },
            { nome: "André Silva", pos: "ATA", num: 17, forca: 77 }
        ]
    },
    {
        id: "santos",
        nome: "Santos",
        apelido: "Peixe",
        pote: "A",
        estadio: "Vila Belmiro",
        capacidade: 16795,
        moral: 55,
        status: "Normal",
        cor: "#000000",
        jogadores: [
            { nome: "João Paulo", pos: "GOL", num: 34, forca: 82 },
            { nome: "JP Chermont", pos: "LAT", num: 13, forca: 78 },
            { nome: "Gil", pos: "ZAG", num: 4, forca: 80 },
            { nome: "Jair", pos: "ZAG", num: 33, forca: 79 },
            { nome: "Escobar", pos: "LAT", num: 31, forca: 76 },
            { nome: "João Schmidt", pos: "MEI", num: 5, forca: 81 },
            { nome: "Diego Pituca", pos: "MEI", num: 21, forca: 80 },
            { nome: "Giuliano", pos: "MEI", num: 20, forca: 79 },
            { nome: "Guilherme", pos: "ATA", num: 11, forca: 81 },
            { nome: "Furch", pos: "ATA", num: 9, forca: 79 },
            { nome: "Neymar Jr", pos: "ATA", num: 10, forca: 94 },
            { nome: "Brazão", pos: "GOL", num: 77, forca: 75 },
            { nome: "Aderlan", pos: "LAT", num: 12, forca: 74 },
            { nome: "Sandry", pos: "MEI", num: 6, forca: 75 },
            { nome: "Otero", pos: "MEI", num: 22, forca: 78 }
        ]
    },
    {
        id: "bragantino",
        nome: "Red Bull Bragantino",
        pote: "B",
        estadio: "Nabi Abi Chedid",
        capacidade: 17128,
        moral: 50,
        status: "Normal",
        jogadores: [
            { nome: "Cleiton", pos: "GOL", num: 1, forca: 83 },
            { nome: "Jadsom", pos: "MEI", num: 5, forca: 79 },
            { nome: "L. Evangelista", pos: "MEI", num: 8, forca: 81 },
            { nome: "Helinho", pos: "ATA", num: 11, forca: 82 },
            { nome: "Eduardo Sasha", pos: "ATA", num: 19, forca: 80 },
            { nome: "Juninho Capixaba", pos: "LAT", num: 29, forca: 80 },
            { nome: "Pedro Henrique", pos: "ZAG", num: 3, forca: 78 },
            { nome: "Luan Cândido", pos: "LAT", num: 36, forca: 79 },
            { nome: "Eric Ramires", pos: "MEI", num: 7, forca: 77 },
            { nome: "Mosquera", pos: "ATA", num: 30, forca: 78 },
            { nome: "Borbas", pos: "ATA", num: 18, forca: 79 },
            { nome: "Lucão", pos: "GOL", num: 12, forca: 72 },
            { nome: "Raul", pos: "MEI", num: 23, forca: 75 }
        ]
    },
    {
        id: "novorizontino",
        nome: "Novorizontino",
        pote: "B",
        estadio: "Jorjão",
        capacidade: 12398,
        moral: 50,
        status: "Normal",
        jogadores: [
            { nome: "Jordi", pos: "GOL", num: 1, forca: 78 },
            { nome: "César Martins", pos: "ZAG", num: 3, forca: 76 },
            { nome: "Rafael Donato", pos: "ZAG", num: 4, forca: 75 },
            { nome: "Reverson", pos: "LAT", num: 6, forca: 74 },
            { nome: "Geovane", pos: "MEI", num: 5, forca: 76 },
            { nome: "Marlon", pos: "MEI", num: 8, forca: 75 },
            { nome: "Waguininho", pos: "ATA", num: 11, forca: 76 },
            { nome: "Neto Pessoa", pos: "ATA", num: 9, forca: 77 },
            { nome: "Patrick", pos: "ZAG", num: 14, forca: 74 },
            { nome: "Willian Farias", pos: "MEI", num: 18, forca: 75 },
            { nome: "Lucca", pos: "ATA", num: 10, forca: 76 },
            { nome: "Airton", pos: "GOL", num: 12, forca: 70 },
            { nome: "Rodolfo", pos: "ATA", num: 19, forca: 73 }
        ]
    },
    {
        id: "mirassol",
        nome: "Mirassol",
        pote: "B",
        estadio: "Maião",
        capacidade: 18000,
        moral: 50,
        status: "Normal",
        jogadores: [
            { nome: "Alex Muralha", pos: "GOL", num: 1, forca: 77 },
            { nome: "Lucas Gazal", pos: "ZAG", num: 3, forca: 74 },
            { nome: "Luiz Otávio", pos: "ZAG", num: 4, forca: 75 },
            { nome: "Warley", pos: "LAT", num: 2, forca: 73 },
            { nome: "Danielzinho", pos: "MEI", num: 8, forca: 76 },
            { nome: "Gabriel", pos: "MEI", num: 5, forca: 75 },
            { nome: "Chico Kim", pos: "MEI", num: 10, forca: 77 },
            { nome: "Dellatorre", pos: "ATA", num: 49, forca: 78 },
            { nome: "Fernandinho", pos: "ATA", num: 11, forca: 76 },
            { nome: "Negueba", pos: "ATA", num: 7, forca: 75 },
            { nome: "Rodrigo Ferreira", pos: "LAT", num: 16, forca: 74 },
            { nome: "Vanderlei", pos: "GOL", num: 12, forca: 70 },
            { nome: "Yuri", pos: "MEI", num: 15, forca: 73 }
        ]
    },
    {
        id: "saobernardo",
        nome: "São Bernardo",
        pote: "B",
        estadio: "Primeiro de Maio",
        capacidade: 15759,
        moral: 50,
        status: "Normal",
        jogadores: [
            { nome: "Alex Alves", pos: "GOL", num: 1, forca: 76 },
            { nome: "Helder", pos: "ZAG", num: 3, forca: 74 },
            { nome: "Alan Santos", pos: "ZAG", num: 4, forca: 73 },
            { nome: "Vitor Ricardo", pos: "LAT", num: 2, forca: 72 },
            { nome: "Rodrigo Souza", pos: "MEI", num: 5, forca: 75 },
            { nome: "Lucas Lima", pos: "MEI", num: 10, forca: 78 },
            { nome: "Silvinho", pos: "ATA", num: 11, forca: 74 },
            { nome: "Kayke", pos: "ATA", num: 9, forca: 75 },
            { nome: "Arthur Henrique", pos: "LAT", num: 6, forca: 73 },
            { nome: "Romisson", pos: "MEI", num: 8, forca: 74 },
            { nome: "João Carlos", pos: "ATA", num: 19, forca: 73 },
            { nome: "Junior", pos: "GOL", num: 12, forca: 69 },
            { nome: "Davó", pos: "ATA", num: 99, forca: 74 }
        ]
    },
    {
        id: "pontepreta",
        nome: "Ponte Preta",
        pote: "C",
        estadio: "Moisés Lucarelli",
        capacidade: 19728,
        moral: 45,
        status: "Instável",
        jogadores: [
            { nome: "Pedro Rocha", pos: "GOL", num: 1, forca: 75 },
            { nome: "Mateus Silva", pos: "ZAG", num: 3, forca: 73 },
            { nome: "Sérgio Raphael", pos: "ZAG", num: 4, forca: 72 },
            { nome: "Igor Inocêncio", pos: "LAT", num: 2, forca: 71 },
            { nome: "Emerson Santos", pos: "MEI", num: 5, forca: 73 },
            { nome: "Elvis", pos: "MEI", num: 10, forca: 78 },
            { nome: "Dodô", pos: "MEI", num: 8, forca: 72 },
            { nome: "Jeh", pos: "ATA", num: 9, forca: 76 },
            { nome: "Iago Dias", pos: "ATA", num: 11, forca: 73 },
            { nome: "Gabriel Risso", pos: "LAT", num: 6, forca: 71 },
            { nome: "Dudu Hatamoto", pos: "ATA", num: 7, forca: 70 },
            { nome: "Luan", pos: "GOL", num: 12, forca: 68 },
            { nome: "Ramon", pos: "MEI", num: 15, forca: 71 }
        ]
    },
    {
        id: "guarani",
        nome: "Guarani",
        pote: "C",
        estadio: "Brinco de Ouro",
        capacidade: 29130,
        moral: 45,
        status: "Instável",
        jogadores: [
            { nome: "Vladimir", pos: "GOL", num: 1, forca: 74 },
            { nome: "Douglas", pos: "ZAG", num: 3, forca: 73 },
            { nome: "Léo Santos", pos: "ZAG", num: 4, forca: 72 },
            { nome: "Diogo Mateus", pos: "LAT", num: 13, forca: 73 },
            { nome: "Matheus Bueno", pos: "MEI", num: 5, forca: 74 },
            { nome: "Luan Dias", pos: "MEI", num: 10, forca: 76 },
            { nome: "Caio Dantas", pos: "ATA", num: 9, forca: 77 },
            { nome: "Airton", pos: "ATA", num: 11, forca: 73 },
            { nome: "Jefferson", pos: "LAT", num: 6, forca: 71 },
            { nome: "Camacho", pos: "MEI", num: 8, forca: 72 },
            { nome: "João Victor", pos: "ATA", num: 7, forca: 72 },
            { nome: "Pegorari", pos: "GOL", num: 12, forca: 71 },
            { nome: "Chay", pos: "MEI", num: 20, forca: 74 }
        ]
    },
    {
        id: "portuguesa",
        nome: "Portuguesa",
        pote: "C",
        estadio: "Estádio do Canindé",
        capacidade: 21004,
        moral: 60,
        status: "Motivada",
        jogadores: [
            { nome: "Thomazella", pos: "GOL", num: 1, forca: 74 },
            { nome: "Quintana", pos: "ZAG", num: 3, forca: 72 },
            { nome: "Patrick", pos: "ZAG", num: 4, forca: 71 },
            { nome: "Douglas Borel", pos: "LAT", num: 2, forca: 70 },
            { nome: "Tauã", pos: "MEI", num: 5, forca: 71 },
            { nome: "Giovanni Augusto", pos: "MEI", num: 10, forca: 76 },
            { nome: "Maceió", pos: "ATA", num: 11, forca: 72 },
            { nome: "Henrique Dourado", pos: "ATA", num: 9, forca: 75 },
            { nome: "Eduardo Diniz", pos: "LAT", num: 6, forca: 70 },
            { nome: "Ricardinho", pos: "MEI", num: 8, forca: 72 },
            { nome: "Victor Andrade", pos: "ATA", num: 7, forca: 73 },
            { nome: "Rafael Pascoal", pos: "GOL", num: 12, forca: 68 },
            { nome: "Chrigor", pos: "ATA", num: 19, forca: 71 }
        ]
    },
    {
        id: "veloclube",
        nome: "Velo Clube",
        pote: "C",
        estadio: "Benitão",
        capacidade: 8136,
        moral: 70,
        status: "Empolgação",
        jogadores: [
            { nome: "Gabriel Félix", pos: "GOL", num: 1, forca: 70 },
            { nome: "Cezane", pos: "ZAG", num: 3, forca: 68 },
            { nome: "Julio Vaz", pos: "ZAG", num: 4, forca: 67 },
            { nome: "Samoel Pizzi", pos: "LAT", num: 2, forca: 68 },
            { nome: "Norton", pos: "MEI", num: 5, forca: 69 },
            { nome: "Felipinho", pos: "MEI", num: 10, forca: 71 },
            { nome: "Lucas Duni", pos: "ATA", num: 9, forca: 70 },
            { nome: "Douglas Skilo", pos: "ATA", num: 11, forca: 69 },
            { nome: "Léo Campos", pos: "LAT", num: 6, forca: 67 },
            { nome: "Martineli", pos: "MEI", num: 8, forca: 68 },
            { nome: "Gaia", pos: "ZAG", num: 14, forca: 66 },
            { nome: "Dã", pos: "GOL", num: 12, forca: 65 },
            { nome: "Rian", pos: "ATA", num: 17, forca: 68 }
        ]
    },
    {
        id: "botafogosp",
        nome: "Botafogo-SP",
        pote: "D",
        estadio: "Santa Cruz",
        capacidade: 29292,
        moral: 50,
        status: "Normal",
        jogadores: [
            { nome: "Michael", pos: "GOL", num: 1, forca: 74 },
            { nome: "Lucas Dias", pos: "ZAG", num: 3, forca: 72 },
            { nome: "Schappo", pos: "ZAG", num: 4, forca: 71 },
            { nome: "Wallison", pos: "LAT", num: 2, forca: 72 },
            { nome: "Matheus Barbosa", pos: "MEI", num: 5, forca: 73 },
            { nome: "Leandro Maciel", pos: "MEI", num: 10, forca: 74 },
            { nome: "Alex Sandro", pos: "ATA", num: 9, forca: 73 },
            { nome: "Douglas Baggio", pos: "ATA", num: 11, forca: 74 },
            { nome: "Jean Victor", pos: "LAT", num: 6, forca: 71 },
            { nome: "Filipe Soutto", pos: "MEI", num: 8, forca: 72 },
            { nome: "Toró", pos: "ATA", num: 7, forca: 72 },
            { nome: "João Carlos", pos: "GOL", num: 12, forca: 69 },
            { nome: "Thássio", pos: "LAT", num: 13, forca: 70 }
        ]
    },
    {
        id: "noroeste",
        nome: "Noroeste",
        pote: "D",
        estadio: "Alfredo de Castilho",
        capacidade: 18866,
        moral: 55,
        status: "Normal",
        jogadores: [
            { nome: "Reynaldo", pos: "GOL", num: 1, forca: 69 },
            { nome: "Luizão", pos: "ZAG", num: 3, forca: 67 },
            { nome: "Maycon", pos: "ZAG", num: 4, forca: 68 },
            { nome: "Balardin", pos: "LAT", num: 2, forca: 66 },
            { nome: "Jonatas Paulista", pos: "MEI", num: 5, forca: 67 },
            { nome: "Pereira", pos: "MEI", num: 10, forca: 70 },
            { nome: "Carlão", pos: "ATA", num: 9, forca: 71 },
            { nome: "Barcos", pos: "ATA", num: 11, forca: 68 },
            { nome: "PH", pos: "LAT", num: 6, forca: 66 },
            { nome: "Matheus Blade", pos: "MEI", num: 8, forca: 67 },
            { nome: "Isael", pos: "ATA", num: 7, forca: 68 },
            { nome: "Tales", pos: "GOL", num: 12, forca: 64 },
            { nome: "Rodolfo", pos: "MEI", num: 15, forca: 66 }
        ]
    },
    {
        id: "capivariano",
        nome: "Capivariano",
        pote: "D",
        estadio: "Arena Capivari",
        capacidade: 14651,
        moral: 50,
        status: "Normal",
        jogadores: [
            { nome: "Anderson", pos: "GOL", num: 1, forca: 68 },
            { nome: "Leonan", pos: "ZAG", num: 3, forca: 66 },
            { nome: "Jemmes", pos: "ZAG", num: 4, forca: 65 },
            { nome: "Lucas Cerqueira", pos: "LAT", num: 2, forca: 65 },
            { nome: "Bruno Silva", pos: "MEI", num: 5, forca: 67 },
            { nome: "Thiaguinho", pos: "MEI", num: 10, forca: 69 },
            { nome: "Neto Costa", pos: "ATA", num: 9, forca: 68 },
            { nome: "Paulinho", pos: "ATA", num: 11, forca: 67 },
            { nome: "Tarcísio", pos: "LAT", num: 6, forca: 64 },
            { nome: "Carlos Eduardo", pos: "MEI", num: 8, forca: 66 },
            { nome: "Gustavo Nescau", pos: "ATA", num: 7, forca: 68 },
            { nome: "Douglas", pos: "GOL", num: 12, forca: 63 },
            { nome: "Corrêa", pos: "MEI", num: 15, forca: 65 }
        ]
    },
    {
        id: "primavera",
        nome: "Primavera",
        pote: "D",
        estadio: "Gigante da Vila Industrial",
        capacidade: 8020,
        moral: 50,
        status: "Normal",
        jogadores: [
            { nome: "Gledson", pos: "GOL", num: 1, forca: 67 },
            { nome: "Reginaldo", pos: "ZAG", num: 3, forca: 66 },
            { nome: "Renato Vischi", pos: "ZAG", num: 4, forca: 65 },
            { nome: "Elias", pos: "LAT", num: 2, forca: 64 },
            { nome: "Bonassa", pos: "MEI", num: 5, forca: 66 },
            { nome: "Renatinho", pos: "MEI", num: 10, forca: 68 },
            { nome: "Patrick Fabiano", pos: "ATA", num: 9, forca: 69 },
            { nome: "Dener", pos: "ATA", num: 11, forca: 67 },
            { nome: "Tiago Silva", pos: "LAT", num: 6, forca: 64 },
            { nome: "João Pedro", pos: "MEI", num: 8, forca: 65 },
            { nome: "Luiz Thiago", pos: "ATA", num: 7, forca: 67 },
            { nome: "André Luiz", pos: "GOL", num: 12, forca: 62 },
            { nome: "Luan", pos: "MEI", num: 15, forca: 64 }
        ]
    }
];

if (typeof window !== 'undefined') {
    window.timesData = timesData;
}
// Fim do arquivo, sem chaves extras